### ISSUE TITLE
ESLint Guideline

### ISSUE THREAD

**Issue by lijunle** [lijunle/depcheck-es6#10]
Leverage ESLint instead of JSLint.

I prefer to use [Airbnb JavaScript guideline](https://github.com/airbnb/javascript/tree/master/linters).

**Comment by woodb** [comment]
> I prefer to use Airbnb JavaScript guideline.

100% agreed :+1: I like to roll with this `.eslintrc` lately...

```
{
  "extends": "airbnb",
  "rules": {
    "new-cap": 0
  }
}
```

**Comment by lijunle** [comment]
Instead, there could be a great work before reach here. 
- [x] Enable ES6 syntax
- [x] Use single quote for strings, instead of double quote
- [x] Resolve other linter warnings.

**Comment by lijunle** [comment]
Current ESLint violation rules. The '(x)' after each rule name indicates the count of codes violate that rule. The full table is [here](https://gist.github.com/lijunle/a11fe2ecc0d8ae4f6ac1#file-eslint-result-md).

Both these two tables will be updated continuously.

---

Total violated rules: 34, places: 265
- [x] comma-dangle: Missing trailing comma. (7)
- [x] comma-spacing: There should be no space before ','. (2)
- [x] func-names: Missing function expression name. (16)
- [x] indent: Expected indentation of 2 space characters but found 4. (1)
- [x] indent: Expected indentation of 4 space characters but found 6. (6)
- [x] no-console: Unexpected console statement. (13)
- [x] no-empty: Empty block statement. (1)
- [x] no-param-reassign: Assignment to function parameter 'deps'. (2)
- [x] no-param-reassign: Assignment to function parameter 'devDeps'. (2)
- [x] no-shadow: path is already declared in the upper scope. (2)
- [x] no-unused-vars: "a" is defined but never used (2)
- [x] no-unused-vars: "bar" is defined but never used (2)
- [x] no-unused-vars: "barfoo" is defined but never used (2)
- [x] no-unused-vars: "c" is defined but never used (2)
- [x] no-unused-vars: "d" is defined but never used (2)
- [x] no-unused-vars: "e" is defined but never used (2)
- [x] no-unused-vars: "foo" is defined but never used (2)
- [x] no-unused-vars: "h" is defined but never used (2)
- [x] no-unused-vars: "i" is defined but never used (2)
- [x] no-unused-vars: "j" is defined but never used (2)
- [x] no-unused-vars: "member" is defined but never used (2)
- [x] no-unused-vars: "name" is defined but never used (2)
- [x] no-unused-vars: "optimist" is defined but never used (2)
- [x] no-unused-vars: "pkg" is defined but never used (1)
- [x] no-unused-vars: "star" is defined but never used (2)
- [x] no-use-before-define: filterDependencies was used before it was defined (2)
- [x] no-use-before-define: run was used before it was defined (1)
- [x] no-var: Unexpected var, use let or const instead. (53)
- [x] padded-blocks: Block must not be padded by blank lines. (2)
- [x] quotes: Strings must use singlequote. (97)
- [x] semi: Missing semicolon. (1)
- [x] space-before-function-paren: Unexpected space before function parentheses. (12)
- [x] undefined: Unexpected token (1)
- [x] vars-on-top: All "var" declarations must be at the top of the function scope. (15)

**Comment by lijunle** [comment]
@woodb 

Could you help to resolve these ESLint warnings together :smiley: ? I will resolve from the top, you could from the bottom if you have time. :baby_chick: 

If you encounter one hard to resolve, just skip it.

If you send RP, please diff with `eslint` branch and I will merge to #32. Once we get a :white_check_mark: , we can merge into `master` branch.

For the current ESLint violated warnings, two ways to find them:
- Generate from [my utility](https://gist.github.com/lijunle/a11fe2ecc0d8ae4f6ac1#file-eslint-result-js).
- Check on [Travis build output](https://travis-ci.org/lijunle/depcheck-es6/jobs/81384005#L445).

**Comment by woodb** [comment]
Hey @lijunle, yep I can help after 21:00 UTC today, pretty slammed until then...

**Comment by lijunle** [comment]
@woodb I have taken care of all the ESLint warnings. Thanks any way. :smiley:
