### ISSUE TITLE
api error

### ISSUE THREAD

**Issue by tek0** [lijunle/depcheck-es6#105]
Hi,

I tried calling api from my code, I am getting the following error, can you tell me why its happening.

-MacBook-Pro:todomvc $ npm install
npm WARN package.json redux-todomvc-example@0.0.0 No README data
npm WARN package.json react-addons-test-utils@0.14.0 No repository field.

> redux-todomvc-example@0.0.0 install /Users/Desktop/FrontEnd/redux-master/examples/todomvc
> node test-depcheck.js

testing
module.js:338
    throw err;
          ^
Error: Cannot find module '/path/to/your/project/package.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at depcheck (/Users/Desktop/FrontEnd/redux-master/examples/todomvc/node_modules/depcheck-es6/dist/index.js:251:40)
    at Object.<anonymous> (/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test-depcheck.js:31:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! redux-todomvc-example@0.0.0 install: `node test-depcheck.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the redux-todomvc-example@0.0.0 install script 'node test-depcheck.js'.
npm ERR! This is most likely a problem with the redux-todomvc-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node test-depcheck.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls redux-todomvc-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Desktop/FrontEnd/redux-master/examples/todomvc/npm-debug.log

https://github.com/lijunle/depcheck-es6#api

Thanks,

**Comment by lijunle** [comment]
Please share your `test-depcheck.js` .

From the log, this is the cause:

> Error: Cannot find module '/path/to/your/project/package.json'

**Comment by tek0** [comment]
@lijunle providing it below. 

It prints both this values 
console.log("testing");
console.log("after options" +options);
but does not print last line
console.log("lastline");

``` js
console.log("testing");

var path = require('path');
var depcheck = require('depcheck-es6');

var options = {
  withoutDev: false, // check against devDependencies
  ignoreBinPackage: false, // ignore the packages with bin entry
  ignoreDirs: [ // folder with these names will be ignored
    'sandbox',
    'dist',
    'bower_components'
  ],
  ignoreMatches: [ // ignore dependencies that matches these globs
    'grunt-*'
  ],
  parsers: { // the target parsers
    '*.js': depcheck.parser.es6,
    '*.jsx': depcheck.parser.jsx
  },
  detectors: [ // the target detectors
    depcheck.detector.requireCallExpression,
    depcheck.detector.importDeclaration
  ],
  specials: [ // the target special parsers
    depcheck.special.eslint,
    depcheck.special.webpack
  ]
};
console.log("after options" +options);


depcheck('/path/to/your/project', options, function(unused) {
  console.log(unused.dependencies); // an array containing the unused dependencies
  console.log(unused.devDependencies); // an array containing the unused devDependencies
  console.log(unused.invalidFiles); // files that cannot access or parse
  console.log(unused.invalidDirs); // directories that cannot access
});

console.log("lastline");
```

---

_Modified by Junle to wrap the code inside `````._

**Comment by lijunle** [comment]
You need to modify the `depcheck` parameter - replace your real path to `'/path/to/your/project'`. Besides, you need to pass your options too. The options show in the home page does **not** work, it is for demonstration only.

**Comment by tek0** [comment]
@lijunle I changed the folder but still I am getting the below error, am I doing anything wrong
can you give an example how to modify options too

Code

``` js
//console.log("testing");

var path = require('path');
var depcheck = require('depcheck-es6');
//console.log("depcheck" +depcheck);

var options = {
  withoutDev: false, // check against devDependencies
  ignoreBinPackage: false, // ignore the packages with bin entry
  ignoreDirs: [ // folder with these names will be ignored
    'sandbox',
    'dist',
    'bower_components'
  ],
  ignoreMatches: [ // ignore dependencies that matches these globs
    'grunt-*'
  ],
  parsers: { // the target parsers
    '*.js': depcheck.parser.es6,
    '*.jsx': depcheck.parser.jsx
  },
  detectors: [ // the target detectors
    depcheck.detector.requireCallExpression,
    depcheck.detector.importDeclaration
  ],
  specials: [ // the target special parsers
    depcheck.special.eslint,
    depcheck.special.webpack
  ]
};
//console.log("after options" +options);


depcheck('/Users/Desktop/FrontEnd/redux-master/examples/todomvc', options, function(unused) {
  console.log(unused.dependencies); // an array containing the unused dependencies
  console.log(unused.devDependencies); // an array containing the unused devDependencies
  console.log(unused.invalidFiles); // files that cannot access or parse
  console.log(unused.invalidDirs); // directories that cannot access
});

//console.log("lastline");


```

Error

npm install
npm WARN package.json redux-todomvc-example@0.0.0 No README data
npm WARN package.json react-addons-test-utils@0.14.0 No repository field.

> redux-todomvc-example@0.0.0 install /Users/Desktop/FrontEnd/redux-master/examples/todomvc
> node test-depcheck.js

[ 'classnames',
  'depcheck-es6',
  'react',
  'react-dom',
  'react-redux',
  'redux' ]
[ 'babel-core',
  'babel-loader',
  'babel-plugin-react-transform',
  'expect',
  'express',
  'jsdom',
  'mocha',
  'node-libs-browser',
  'raw-loader',
  'react-addons-test-utils',
  'react-transform-hmr',
  'style-loader',
  'todomvc-app-css',
  'webpack',
  'webpack-dev-middleware',
  'webpack-hot-middleware' ]
{ '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/.DS_Store': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/.babelrc': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/actions/todos.js': [TypeError: object is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/components/Footer.js': [TypeError: object is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/components/Header.js': [TypeError: object is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/components/MainSection.js': [TypeError: object is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/components/TodoItem.js': [TypeError: object is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/components/TodoTextInput.js': [TypeError: object is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/constants/ActionTypes.js': [TypeError: object is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/constants/TodoFilters.js': [TypeError: object is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/containers/App.js': [TypeError: object is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/index.html': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/index.js': [TypeError: object is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/package.json': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/reducers/index.js': [TypeError: object is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/reducers/todos.js': [TypeError: object is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/server.js': [TypeError: object is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/store/configureStore.js': [TypeError: object is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test/actions/todos.spec.js': [TypeError: object is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test/components/Footer.spec.js': [TypeError: object is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test/components/Header.spec.js': [TypeError: object is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test/components/MainSection.spec.js': [TypeError: object is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test/components/TodoItem.spec.js': [TypeError: object is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test/components/TodoTextInput.spec.js': [TypeError: object is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test/reducers/todos.spec.js': [TypeError: object is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test/setup.js': [TypeError: object is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test-depcheck.js': [TypeError: object is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/webpack.config.js': [TypeError: object is not a function] }
{}

**Comment by lijunle** [comment]
Pass an empty object as option. Again, the option shown in home page is for demonstration only.

**Comment by tek0** [comment]
@lijunle yeah its working if i give empty options, but when I test it with specail parser for webpack its throwing an error

Can you tell me where should I need to include this part of code, to check custom special parser
https://github.com/lijunle/depcheck-es6/blob/master/doc/pluggable-design.md#implement-custom-special-parser 

Error

npm install
npm WARN package.json redux-todomvc-example@0.0.0 No README data
npm WARN package.json react-addons-test-utils@0.14.0 No repository field.

> redux-todomvc-example@0.0.0 install /Users/Desktop/FrontEnd/redux-master/examples/todomvc
> node test-depcheck.js

[]
[ 'babel-loader',
  'babel-plugin-react-transform',
  'express',
  'node-libs-browser',
  'raw-loader',
  'react-transform-hmr',
  'style-loader' ]
{ '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/.DS_Store': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/.babelrc': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/actions/todos.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/components/Footer.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/components/Header.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/components/MainSection.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/components/TodoItem.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/components/TodoTextInput.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/constants/ActionTypes.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/constants/TodoFilters.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/containers/App.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/index.html': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/index.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/package.json': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/reducers/index.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/reducers/todos.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/server.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/store/configureStore.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test/actions/todos.spec.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test/components/Footer.spec.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test/components/Header.spec.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test/components/MainSection.spec.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test/components/TodoItem.spec.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test/components/TodoTextInput.spec.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test/reducers/todos.spec.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test/setup.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test-depcheck.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/webpack.config.js': [TypeError: undefined is not a function] }
{}

**Comment by lijunle** [comment]
> when I test it with specail parser for webpack its throwing an error

That is caused by the webpack special parser has not been implemented yet. Tracked by #14.

If you want to leverage custom special parser, add the following to your options: 

``` js
function mySpecialParser(...) {...} // implement by myself

const opts = {
  specials: [
    mySpecialParser
  ]
}
```

You can reference the [ESLint special parser](https://github.com/lijunle/depcheck-es6/blob/master/src/special/eslint.js), which is exposed as `depcheck.special.eslint`. Its code logic is simple,

**Comment by tek0** [comment]
@lijunle is it the same logic or different logic for webpack, if its different can atleast tell logic how to implement
https://github.com/lijunle/depcheck-es6/blob/master/src/special/eslint.js

**Comment by lijunle** [comment]
> is it the same logic or different logic for webpack,

Each special parser should have its own logic. If they are the same, why implement it twice? That does not make sense.

> if its different can atleast tell logic how to implement

Sorry, now I have no idea on how to implement it. If you are going to implement it, please read the docs and source code of webpack to get the ideas. I appreciate your contribution.

**Comment by tek0** [comment]
@lijunle  thanks for your reply, I created a  sample file for writing a special parser in depcheck-es6/dis/special and named that file name as webpack.js, there in webpack.js, I am trying to print to print a statement but its not printing, providing my code below

> webpack.js
> 
> ``` js
> console.log("testing-webpack-special-parser");
> ```
> 
> test-depcheck.js
> 
> ``` js
> //console.log("testing");
> var path = require('path');
> var depcheck = require('depcheck-es6');
> //console.log("depcheck" +depcheck);
> var options = {
>   specials: [ // the target special parsers
>     depcheck.special.webpack
>   ]
> };
> //console.log("after options" +options);
> depcheck('/Users/Raj/Desktop/FrontEnd/redux-master/examples/todomvc', options, function(unused) {
>   console.log(unused.dependencies); // an array containing the unused dependencies
>   console.log(unused.devDependencies); // an array containing the unused devDependencies
>   console.log(unused.invalidFiles); // files that cannot access or parse
>   console.log(unused.invalidDirs); // directories that cannot access
> });
> //console.log("lastline");
> ```
> 
> error
> 
> ``` js
> npm install
> npm WARN package.json redux-todomvc-example@0.0.0 No README data
> npm WARN package.json react-addons-test-utils@0.14.0 No repository field.
> 
> redux-todomvc-example@0.0.0 install /Users/Desktop/FrontEnd/redux-master/examples/todomvc
> node test-depcheck.js
> ```

[]
[ 'babel-loader',
  'babel-plugin-react-transform',
  'express',
  'node-libs-browser',
  'raw-loader',
  'react-transform-hmr',
  'style-loader' ]
{ '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/.DS_Store': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/.babelrc': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/actions/todos.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/components/Footer.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/components/Header.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/components/MainSection.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/components/TodoItem.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/components/TodoTextInput.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/constants/ActionTypes.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/constants/TodoFilters.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/containers/App.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/index.html': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/index.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/package.json': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/reducers/index.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/reducers/todos.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/server.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/store/configureStore.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test/actions/todos.spec.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test/components/Footer.spec.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test/components/Header.spec.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test/components/MainSection.spec.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test/components/TodoItem.spec.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test/components/TodoTextInput.spec.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test/reducers/todos.spec.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test/setup.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/test-depcheck.js': [TypeError: undefined is not a function],
  '/Users/Desktop/FrontEnd/redux-master/examples/todomvc/webpack.config.js': [TypeError: undefined is not a function] }
{}

```
```

**Comment by lijunle** [comment]
Your file `depcheck-es6/dis/special` will not be `depcheck.special.webpack` automatically.

You need to require it, just as you do for depcheck package - `var webpackSpecial = require('./depcheck-es6/dis/special')`, then pass `webpackSpecial` variable to special array.

**Comment by tek0** [comment]
@lijunle 
its printing only this line
console.log("webpack-file-special-parser");

its not printing below line, can you tell me why
  console.log("inside wrapToArray");
    console.log("inside webpack");
      console.log("airbnbResult");
  console.log("no airbnbResult");

``` js
'use strict';
console.log("webpack-file-special-parser");
var _interopRequireDefault = require('babel-runtime/helpers/interop-require-default')['default'];

Object.defineProperty(exports, '__esModule', {
  value: true
});

var _path = require('path');

var _path2 = _interopRequireDefault(_path);

function wrapToArray(obj) {
  console.log("inside wrapToArray");
  if (!obj) {
    return [];
  } else if (obj instanceof Array) {
    return obj;
  }

  return [obj];
}

function checkAirbnb(configs) {
  if (configs.indexOf('webpack') !== -1) {
    console.log("inside webpack");
    return ['eslint-config-airbnb', 'babel-eslint', 'eslint-plugin-react', 'eslint'];
  } else if (configs.indexOf('airbnb/base') !== -1) {
    return ['eslint-config-airbnb', 'babel-eslint', 'eslint'];
  } else if (configs.indexOf('airbnb/legacy') !== -1) {
    return ['eslint-config-airbnb', 'eslint'];
  }

  return false;
}

exports['default'] = function (content, filename) {
  var basename = _path2['default'].basename(filename);
  if (basename === '.eslintrc') {
    var configs = wrapToArray(JSON.parse(content)['extends']);

    var airbnbResult = checkAirbnb(configs);
    if (airbnbResult) {
      return airbnbResult;
      console.log("airbnbResult");
    }
    console.log("no airbnbResult");
    return [];
  }

  return [];
};

module.exports = exports['default'];
```

**Comment by lijunle** [comment]
`console.log("webpack-file-special-parser");` is called when node evaluate the file (on `require('...')` call), the others are inside a function. They appear only when the function is called.

I think you could better to google a tutorial and learn the basic node.js knowledge first. [Here](http://stackoverflow.com/questions/2353818/how-do-i-get-started-with-node-js) is a random result.

**Comment by tek0** [comment]
@lijunle ok can you tell me how to print the below lines and see

console.log("inside wrapToArray");
console.log("inside webpack");
console.log("airbnbResult");
console.log("no airbnbResult");

**Comment by lijunle** [comment]
Set it in options.

``` js
var options = {
  specials: [
    depcheck.special.eslint
  ]
};
```

**Comment by tek0** [comment]
@lijunle yeah thats working, I am trying to fetch all the loaders of webpack, is there anyway to fetch all those loaders

**Comment by lijunle** [comment]
I have no idea.
