### ISSUE TITLE
Webpack loader support

### ISSUE THREAD

**Issue by lijunle** [lijunle/depcheck-es6#14]
[Webpack loaders](http://webpack.github.io/docs/loaders.html) are a special way to "load" code into webpack.

There are two syntax to use webpack loader:
- Via `require` function
- Via webpack config file

**Comment by js08** [comment]
@lijunle is the issue fixed

**Comment by lijunle** [comment]
No, not yet. I do not have **full scenario** to support this. If you have a project using webpack, then you can depcheck the project and resolve the webpack issues. I guess webpack might be complex because it use its naming convention to _require_ packages.

**Comment by js08** [comment]
@lijunle to check webpack dependencies do I need to use special commands

**Comment by lijunle** [comment]
Let me clarify, webpack has many loaders, plugins, etc. There is a simple way to depend on one webpack loader/plugin (check [this docs](http://webpack.github.io/docs/using-loaders.html#usage)). Those usages do not follow `require` function call. We may need to some special way to detect them.

Currently, such special command does not exist.

If you want to work on this, read [webpack's document](http://webpack.github.io/docs/) and depcheck's [pluggable design doc](https://github.com/lijunle/depcheck-es6/blob/master/doc/pluggable-design.md).

**Comment by js08** [comment]
@lijunle does this npm package https://github.com/dylang/npm-check supports  webpack

**Comment by lijunle** [comment]
I don't think they support. Npm-check use depcheck to detect unused dependencies.

**Comment by js08** [comment]
@lijunle so are you not checking for packages in devDependencies which is mention in package.json

**Comment by lijunle** [comment]
@js08  I don't get your meaning, is that related to webpack issue? If not, please open another issue.

**Comment by js08** [comment]
@lijunle if npm-check packages supports webpack we can use the same code in depcheck-es6

**Comment by js08** [comment]
@lijunle can you tell what exactly is the issue its confusing

**Comment by js08** [comment]
@lijunle https://github.com/lijunle/depcheck-es6/issues/27 if you look at this it seems you have closed

**Comment by js08** [comment]
@lijunle here is an example for todomvc app, can you fix it https://github.com/rackt/redux/blob/master/examples/todomvc/webpack.config.js#L22

**Comment by lijunle** [comment]
Hi, @js08 

I am sorry to tell you that, I am not going to work on this issue. Because of the estimated complexity of this issue is high, and the benefit is not very high. I will not work on this issue until my another working project reach my bar.

However, if you have ideas on this, please go ahead to implement it. I am welcome for a PR.

**Comment by lijunle** [comment]
This issue was moved to depcheck/depcheck#42
