### ISSUE TITLE
Test coverage reporting by coveralls.io

### ISSUE THREAD

**Issue by woodb** [lijunle/depcheck-es6#16]
It would be good if we got a feel for our test coverage, and assure test coverage moving forward. I've seen other projects using coveralls.io for this purpose, and thought it might be neat to try out.
- [Coveralls.io Node.js documentation](https://coveralls.zendesk.com/hc/en-us/articles/201769715-Javascript-Node)
- [Example travis configuration for a JavaScript project](https://github.com/graphql/graphql-js/blob/29eff45d1c4b4cf8570311544abed1cee774803a/.travis.yml)

**Comment by lijunle** [comment]
@winniehell has [a commit](https://github.com/winniehell-forks/depcheck/commit/2b2c8de0a54a7e01de0d5899418d1f82bc6d1a22) (on rumpl/depcheck#25) on the half of this.

Please port the commit to here.

**Comment by lijunle** [comment]
Close via #19
