### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by woodb** [lijunle/depcheck-es6#2]
Thanks for doing this, I think it was necessary! Thought I'd make this issue just so I got the notification for when it got published on npm :)

**Comment by lijunle** [comment]
I have push a private build to NPM: https://www.npmjs.com/package/depcheck-es6

Please help testing it. I am handling the Travis issue. If OK, I will push the bits to this repo.

**Comment by lijunle** [comment]
_Update_: The published bits have been pushed to this project.

**Comment by woodb** [comment]
> Please help testing it.

Roger that, my main motivation is to get dylang/npm-check#17 closed out, so I'm working with using your fork with this code. It was able to find more of my ES6 imports, but not all. Still investigating on whether that's an `npm-check` issue first.

**Comment by woodb** [comment]
Actually, I was mistaken, it works perfectly! Awesome!
