### ISSUE TITLE
JSX Support

### ISSUE THREAD

**Issue by woodb** [lijunle/depcheck-es6#8]
I saw you were working on this on the [jsx-support branch](https://github.com/lijunle/depcheck-es6/tree/jsx-support), any plans to push this ahead?

**Comment by lijunle** [comment]
That is an old branch, which is proposed to send PR to rumpl. It works fine offline.

However, that changes like a hack - it supports JSX but when another syntax comes (e.g., [Riot.js](http://riotjs.com/)), it needs another hack on it. So, I am thinking a way to make the support as a module.

---

Some basic ideas...

The JSX support is a magic to [parse content to AST](https://github.com/rumpl/depcheck/commit/842f5af4e972c014ea2a0b802cc793ff6e50022b#diff-168726dbe96b3ce427e7fedce31bb0bcR44). We could make this magic extensible.
