### ISSUE TITLE
Parser for coffeescript

### ISSUE THREAD

**Issue by mathieudutour** [lijunle/depcheck-es6#80]
Adding a parser for coffeescript files would be awesome.

I'm not familiar with the code, we just need to find a parser?

**Comment by lijunle** [comment]
Sorry, I am finding the root cause of #79. I will look into this when have time.

**Comment by lijunle** [comment]
@mathieudutour I proposed a RP #82 for this. 

For simplicity, I just compile the CoffeeScript to JavaScript then construct the JavaScript AST from the generated JavaScript. This may get a bad performance.

Do you have suggestions?

**Comment by mathieudutour** [comment]
No, looks good :+1:

**Comment by js08** [comment]
@lijunle can we close it now

**Comment by lijunle** [comment]
Not yet. @mathieudutour proposed another solution to support CoffeeScript. See #84.

**Comment by js08** [comment]
@lijunle he committed right, you can close it right

**Comment by lijunle** [comment]
Merged!

**Comment by lijunle** [comment]
Release 0.5.6 to include this feature.
