### ISSUE TITLE
 *react-redux and *classnames package bug

### ISSUE THREAD

**Issue by js08** [lijunle/depcheck-es6#88]
Hi,

We have tested the depcheck-es6 package with a sample todo react app, but its not recognizing  the *react-redux and *classnames package. We are using the npm version : 2.11.3 and node version: v0.12.7.

You can see in the code where they have used react-redux and classnames packages
 https://github.com/rackt/redux/blob/master/examples/todomvc/containers/App.js
 import { connect } from 'react-redux';

 https://github.com/rackt/redux/blob/master/examples/todomvc/components/TodoTextInput.js
 import classnames from 'classnames';

 Providing the output below.
## depcheck-es6

D:\todomvc>.\node_modules.bin\depcheck
Unused Dependencies
- classnames
- react-redux

Unused devDependencies
- babel-core
- babel-loader
- jsdom
- node-libs-browser
- raw-loader
- react-hot-loader
- style-loader
- todomvc-app-css

Thanks

**Comment by lijunle** [comment]
The React parser only detect on `.jsx` file extension.

However, you can try this:

```
.\node_modules.bin\depcheck --parsers="*.js:jsx"
```

**Comment by js08** [comment]
@lijunle its working but its not finding this package alone *jsdom

https://github.com/rackt/redux/blob/master/examples/todomvc/test/setup.js
import { jsdom } from 'jsdom';

Instead of using this type of extensions, can you make it as a small command

**Comment by lijunle** [comment]
The use of `jsdom` should be found, I have no idea why it not works. Could you please investigate on it?

In regards to the command, it is a small work to wrap the command to a `.cmd` file, or `.sh` file on your side.

However, there is a case in my another project. Babel transforms `.jsx` to `.js` file extension to easy node lookup. After the transform, express view engine stop working because the file extension sucks. Finally, I use `.js` as React component file extension.

So, I am thinking about use React parser in [the code](https://github.com/lijunle/depcheck-es6/blob/master/src/index.js#L36).

**Comment by js08** [comment]
@lijunle can you tell me how to investigate jsdom 
For extensions are you saying you have already made code changes??

**Comment by lijunle** [comment]
Currently, depcheck does not provide any logs. The way to investigate is to `console.log`.

No, there is only few lines code to control which parser is used for each file extension. You can read the source code.

**Comment by js08** [comment]
@lijunle can you tell us where to look for that code

**Comment by lijunle** [comment]
Resolved via #96

**Comment by lijunle** [comment]
Ship 0.5.7 as a fix.

**Comment by js08** [comment]
@lijunle 

Hi,

Additionally its not recognizing the following packages, can you fix it

cookie-parser
blueimp-md5

require("http").createServer(function (req, res) {
    // The md5 module exports the md5() function: 
    var md5 = require("./md5").md5,
    // Use the following version if you installed the package with npm: 
    // var md5 = require("blueimp-md5").md5,

**Comment by js08** [comment]
@lijunle can you please reply

**Comment by lijunle** [comment]
Hi, could you please open another issue to track this. I will take a deep look **if I get time**.

Besides...
1. Please wrap your code with ````` to beautify. Reference: https://help.github.com/articles/github-flavored-markdown/
2. Please provide enough code snippet. I don't see neither `cookie-parser` nor `blueimp-md5` is used in your code snippet.
3. Please be patient, everybody gets work to do. **Do not expect quick reply or quick solution.**
