### ISSUE TITLE
Reporting of parsing errors

### ISSUE THREAD

**Issue by woodb** [lijunle/depcheck-es6#9]
Currently no errors are reported if `node-source-walk` [encounters an error while parsing a file](https://github.com/lijunle/depcheck-es6/blob/master/index.js#L51-L53), which makes it tough to differentiate between a file that simply didn't include dependencies and a file with a syntax error.

I'm not sure what the best way to report errors would be... Should it be with a debug option that triggers a `console.debug` or perhaps returns some kind of `ParsingError` object that the calling method can use... or simply re-raise the error?

**Comment by lijunle** [comment]
I don't know how to handle the syntax error either. However does the current depcheck behavior?

**Comment by woodb** [comment]
Currently it just [returns the error](https://github.com/rumpl/depcheck/blob/9e23a5c7c98bb5f88a20ce2f9018052e03fddfba/index.js#L26-L28)

Edit: fixed to look less silly :)

**Comment by lijunle** [comment]
It is not just ignoring it. There is a property `invalidFiles`. It will [capture the parse error files](https://github.com/rumpl/depcheck/blob/9e23a5c7c98bb5f88a20ce2f9018052e03fddfba/index.js#L50-L51) and store in it.

This is a feature break from rumpl's depcheck to this version. We should fix it.

**Comment by lijunle** [comment]
Besides, add test case to cover it first. :cat2:

**Comment by woodb** [comment]
Ah, guess I should read the code I link to :) Agreed

**Comment by lijunle** [comment]
@woodb 

From the [test coverage report](https://coveralls.io/builds/3620054/source?filename=index.js#L77), the `invalidFiles` branch is exactly no test covered.

Could you please continue on the fix?

**Comment by woodb** [comment]
> Could you please continue on the fix?

Yep, I should have some time here soon... Could you please assign this issue to me?

**Comment by lijunle** [comment]
Hi, @woodb I have proposed another fix (#21 ) and will merge it. Thanks for your fix.

**Comment by lijunle** [comment]
Close via #21
