### ISSUE TITLE
Need Support for syntax  "new require('express')();"

### ISSUE THREAD

**Issue by vmc29** [lijunle/depcheck-es6#91]
Hi,

i am facing issue with syntax like "new require('express')();"

showing 'express' unused dependency.
seems to be problem with 'new' keyword.

do we have any solution to incorporate this syntax also.

you can find code here.

https://github.com/rackt/redux/blob/master/examples/todomvc/server.js

Thanks

**Comment by lijunle** [comment]
Hi, @vmc29 

Thanks for your reporting. I have identify your issue in [this commit](https://github.com/lijunle/depcheck-es6/commit/8281cb2554541fcc7ff032c7e3b310bf4a4f3b10).

However, with some deeper investigation, I get some interesting results. Check it:

``` js
// constructor.js
module.exports = function Constructor() {
  console.log(arguments);
  this.name = 'i-am-constructor';
};
```

``` js
// index.js
const instance1 = new require('./constructor')(1, 2, 3);
console.log(instance1);

const instance2 = (new require('./constructor'))(1, 2, 3);
console.log(instance2);

const instance3 = new (require('./constructor'))(1, 2, 3);
console.log(instance3);
```

Run `node index.js`, output:

```
-> % node  index.js
{ '0': 1, '1': 2, '2': 3 }
undefined
{ '0': 1, '1': 2, '2': 3 }
undefined
{ '0': 1, '1': 2, '2': 3 }
Constructor { name: 'i-am-constructor' }
```

You can see that, the first and second call are not right. A pair of parentheses around `require` call is necessary.

**Comment by vmc29** [comment]
Hi lijunle,

Thanks for your response, 
syntax itself needs to be changed in App.

Thanks
