### ISSUE TITLE
instead of rejecting syntax, try another parser

### ISSUE THREAD

**Issue by dylang** [lijunle/depcheck-es6#94]
In [index.js](https://github.com/lijunle/depcheck-es6/blob/master/src/index.js#L110), if the parser throws an error, we give up.

This means `es6` files with the `.js` extension will never parse.

Instead, it should fall back to another parser.

This probably should only happen with `.js` files and if the original parser isn't already `es6`.

**Comment by lijunle** [comment]
> Instead, it should fall back to another parser.

Actually, it will. For example:

Here is the depcheck call:

``` js
depcheck({
  parsers: {
    '*.js': [parser1, parser2, es6]
  }
})
```

Then, for a specified `.js` file, it will examine by `parser1`, `parser2` then `es6`. If `parser1` throws a syntax exception, it will **not** affect `parser2` and `es6` parse the file successfully.

Concretely, the variable `targets` from [this line of code](https://github.com/lijunle/depcheck-es6/blob/master/src/index.js#L132) maps each `parser` to examine independently, so one throws exception will **not** affect the others. The variable name `targets` may be misleading, it actually means target parsers - which its glob is matched.

> This probably should only happen with .js files and if the original parser isn't already es6.

I am not quite sure what this does mean. Could you give an example?

**Comment by dylang** [comment]
> I am not quite sure what this does mean. Could you give an example?

If the filename is `test.es6`, `parser1` might be `es6` and then if that fails, it might use `es6` a second time. I haven't looked at that part of the code to see if that's what really happens.

**Comment by lijunle** [comment]
If the filename is `test.es6`, with the above option (or the existing default option), no parser will work on them. `test.js` is tested because there is [a glob](https://github.com/lijunle/depcheck-es6/blob/master/src/index.js#L36) to match it.

**Comment by lijunle** [comment]
I am closing this issue because follow ups.
