### ISSUE TITLE
Possibility of dependency check for child custom modules

### ISSUE THREAD

**Issue by vmc29** [lijunle/depcheck-es6#98]
Hi @lijunle,

Thanks a lot for great plug-in, it helping us a lot to identify unused dependencies.

As per my understanding, depcheck-es6 will looks in to current package.json and identifies whether dependencies are used in the code or not and list down the results.

is there any possibility to check recursively into custom node_modules and list down the same by special configurations.

![untitled diagram](https://cloud.githubusercontent.com/assets/15243260/10787462/1ab40ae4-7d97-11e5-9671-c1d436aeb7e8.png)

  While i run the "depcheck" against the App/package.json, based on configurations it should do recursive check and provide results in one shot.

Hope my problem is clear to you.. :)

Please guide me if there is possibility, have tried some possibilities, but not succeeded.

Thanks again..

**Comment by lijunle** [comment]
Let me confirm that, you want to check _Custom Module 1_ when you run `depcheck` on App folder?

Why not check it in its own folder? Or run `depcheck ./node_modules/Custom1`?

**Comment by vmc29** [comment]
yes, you are correct..!!! that way it is possible, but i am not able to check for multiple custom modules at a time..

**Comment by lijunle** [comment]
However, why do you want to check on others' module? That sounds like an unnecessary move.

**Comment by vmc29** [comment]
I have multiple custom modules in my App, if i want to see "depcheck" results for all at a time..!!!

it will be helpful..!!!

Thanks

**Comment by lijunle** [comment]
Because of lack full scenario, depcheck might not provide such function. However, you can write a simple script and call depcheck API to check them.

**Comment by js08** [comment]
@lijunle I did investigation on this issue, does he need to make changes to files in detector folder and parser folder, I think it would be great if you give him some directions. Even I am interested in solving the issue

**Comment by lijunle** [comment]
I am closing this issue because follow ups.
